### ISSUE TITLE
where were the tests for ECDSA thumbprints obtained from?

### ISSUE THREAD

**Issue by nhooyr** [square/go-jose#102]
https://github.com/square/go-jose/blob/master/jwk_test.go#L497

Working on adding ECDSA support to [golang.org/x/crypto/acme](https://go-review.googlesource.com/#/c/25462/) but I need a test for ECDSA thumbprints. I copied it from here but I wanted to know where this library got it from.

**Comment by csstaub** [comment]
Here's a list of RFCs that cover JOSE standards, you can find examples in those documents: https://datatracker.ietf.org/wg/jose/documents/
