### ISSUE TITLE
gopkg.in/square/go-jose.v1 fails to build due to unversioned import path

### ISSUE THREAD

**Issue by petercolberg** [square/go-jose#109]
Version 1.0.4 fails to build as a Debian package due to now importing `github.com/square/go-jose/json` instead of previously `gopkg.in/square/go-jose.v1/json`. Could you revert the import path to the latter?

**Comment by csstaub** [comment]
Ah, sorry about that -- I probably made a mistake while rebasing some changes. I'll get it fixed.

**Comment by csstaub** [comment]
Do you have build status online somewhere, or a way I can track these failures directly?

**Comment by petercolberg** [comment]
Debian publishes build logs, but the build is only triggered after the maintainer uploads the new version.

https://buildd.debian.org/status/logs.php?pkg=golang-gopkg-square-go-jose.v1&arch=all
