### ISSUE TITLE
Support decoding and encoding of encrypted-and-signed JWTs

### ISSUE THREAD

**Issue by shaxbee** [square/go-jose#118]
Following up on comment by @jawn in #56.
Will work on adding necessary APIs and implementation shortly.

**Comment by csstaub** [comment]
What changes are required for this?

**Comment by shaxbee** [comment]
I'll provide additional builder and Parse method, so no changes to API, only new functionality. Can be done after v2 release.

**Comment by shaxbee** [comment]
See #125
