### ISSUE TITLE
Support Proof-of-Possession Key Semantics for JSON Web Tokens (JWTs) (RFC 7800) cnf claim

### ISSUE THREAD

**Issue by zamicol** [square/go-jose#119]
Thanks to @shaxbee's additions (#114), there's now JWT claims on the v2 branch.

[RFC 7800](https://tools.ietf.org/html/rfc7800) defines one more claim: cnf.  Now seems like a good time to include it. 

"The value of the "cnf" claim is a JSON object and the members of that object identify the proof-of-possession key."

[Here's the list of JWT claims.](http://www.iana.org/assignments/jwt/jwt.xhtml#IESG)

**Comment by thalesfsp** [comment]
@zamicol @csstaub What's the status of this issue? Thank you!
