### ISSUE TITLE
Support JWT operations in jose-util CLI?

### ISSUE THREAD

**Issue by csstaub** [square/go-jose#121]
The `jose-util` CLI can already decode/dump JWE/JWS for debugging, maybe we should add some JWT debugging commands. Could be useful.

**Comment by shaxbee** [comment]
Also would be nice to have symmetric key support. I guess for jwt I could try deserializing into jwt.Claims to verify if basic structure is correct, and dump the standard claims in human readable form (eg. timestamp).
