### ISSUE TITLE
NewSigner/Verify: accept non-pointer jose.JSONWebKey values

### ISSUE THREAD

**Issue by ericchiang** [square/go-jose#123]
This package is somewhat picky about always using `*jose.JSONWebKey` values instead of non-pointer values. I find myself messing this up a lot, particularly when using JSONWebKeySet[0], which holds concrete values.

Largely I'm surprised when this code:

```go
jwk := jose.JSONWebKey{
	Key:   myRSAKey,
	KeyID: "foobar",
}
options := jose.SigningKey{Algorithm: jose.RS258, Key: jwk}
signer, err := jose.NewSigner(options, nil)
```

Returns the following error.

```
square/go-jose: unsupported key type/format
```

This is because the codebase requires explicitly using a `*JSONWebKey` type instead of a non-pointer value.[1]

```go
func makeJWSRecipient(alg SignatureAlgorithm, signingKey interface{}) (recipientSigInfo, error) {
	switch signingKey := signingKey.(type) {
	// ...
	case *JSONWebKey:
		recipient, err := makeJWSRecipient(alg, signingKey.Key)
		if err != nil {
			return recipientSigInfo{}, err
		}
		recipient.publicKey.KeyID = signingKey.KeyID
		return recipient, nil
	default:
		return recipientSigInfo{}, ErrUnsupportedKeyType
	}
}
```

`Verify()` also has similar logic.

I think this is an issue for `JSONWebKey` types instead of other key types because there's no explicit constructor method (e.g. no `NewJSONWebKey()`). This means I have to explicitly initialize the type myself and end up running into this problem a lot.

Would it be reasonable to add another case statement (probably with a helper method to avoid the repetition)?

```
func makeJWSRecipient(alg SignatureAlgorithm, signingKey interface{}) (recipientSigInfo, error) {
	switch signingKey := signingKey.(type) {
	// ...
	case *JSONWebKey:
		recipient, err := makeJWSRecipient(alg, signingKey.Key)
		if err != nil {
			return recipientSigInfo{}, err
		}
		recipient.publicKey.KeyID = signingKey.KeyID
		return recipient, nil
	case JSONWebKey:
		recipient, err := makeJWSRecipient(alg, signingKey.Key)
		if err != nil {
			return recipientSigInfo{}, err
		}
		recipient.publicKey.KeyID = signingKey.KeyID
		return recipient, nil
	default:
		return recipientSigInfo{}, ErrUnsupportedKeyType
	}
}
```

cc @csstaub

[0] https://godoc.org/gopkg.in/square/go-jose.v2#JSONWebKeySet
[1] https://github.com/square/go-jose/blob/8c5257b2f658f86d174ae68c6a592eaf6a9608d9/signing.go#L133

**Comment by csstaub** [comment]
That's a good point re: not having an explicit constructor method. Adding support for non-pointer JWK sounds totally reasonable to me.

**Comment by shaxbee** [comment]
I actually made that change in my vendored project some time ago, will submit PR shortly.

**Comment by shaxbee** [comment]
See #124

**Comment by csstaub** [comment]
Tagged v2.0.1, closing now. Thanks everyone.
