### ISSUE TITLE
Support setting optional JWT headers

### ISSUE THREAD

**Issue by ekristen** [square/go-jose#126]
See RFC -- https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-5

While the `typ` header is optional it is good practice when creating JWT tokens to set `typ` to `JWT` (see https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-3.1)

**Comment by shaxbee** [comment]
I initially didn't implement it as it wasn't required.
Will add the necessary tpe header shortly.

**Comment by ekristen** [comment]
Would be nice to support all the other headers that are acceptable in a JWS which is used by JWT https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#page-11

**Comment by shaxbee** [comment]
I should have PR for this by the end of the week.

**Comment by mitar** [comment]
Ping on this?

**Comment by mitar** [comment]
What is resolution on this one?
