### ISSUE TITLE
Support Base64URL-encoded "n" parameter in JSONWebKey

### ISSUE THREAD

**Issue by yun-wang** [square/go-jose#130]
The JWA [spec](https://www.rfc-editor.org/rfc/rfc7518.txt) says:

> The "n" (modulus) parameter contains the modulus value for the RSA public key.  It is represented as a Base64urlUInt-encoded value.

However, Base64URL-encoded "n" parameter cannot be unmarshalled into [JSONWebKey](https://github.com/square/go-jose/blob/master/jwk.go#L62) in `go-jose`.

Here is what I'm trying to do:
```go
var d jose.JSONWebKeySet
if err := json.Unmarshal(body, &d); err != nil {
	return err
}
```

When the "n" parameter in the json body is Base64URL encoded instead of Base64 encoded, I get the error `illegal base64 data at input byte 343`. I think this is because `encoding/json` package expects a Base64-encoded string when decoding to [`[]byte`](https://golang.org/pkg/encoding/json/#Marshal).

Not sure if I'm missing something?

This can be solved by changing the type of [`N`](https://github.com/square/go-jose/blob/master/jwk.go#L45) in `rawJSONWebKey` to `string`. If I'm right, let me know, I'll gladly submit a PR.

**Comment by csstaub** [comment]
Do you have an example input? In the struct you linked, [`N`](https://github.com/square/go-jose/blob/v2/jwk.go#L45) is of type `*byteBuffer`, which is a special type that deserializes from [base64url](https://github.com/square/go-jose/blob/v2/encoding.go#L139) already.

**Comment by jsloyer** [comment]
@csstaub below is the result from the jwks endpoint.

```
{
	"keys": [{
		"kty": "RSA",
		"n": "AIbv6q2atH5CgUJauw58enJqDFrpl1h7S0ysbisDwga_omYIGIQey_arOTYt28GkI1cfOXYfenmDIRrBgvvU8WNO8MuDBkbQmlSB1_r026JEF_lH7nMXZt8i3F3Dnaqv0M3D7Jm2bxDLdweI_DQkqsT59WkjZmvex6m9bVWRsASB6kH9R9rIHYZRCqZt5d0rM7nCaZMBtkzuv6o9SUc62FllVWVUzJkLEozUTO6MEH281UruSs88ZMn36voQxC-QAChCa9buHU4wUgeNx3yd5HluOJhk3vXhARbV67W95pBcENvagpEiSBeet1OwFg08UaGYhICciK7f-9oc4RmhdSs=",
		"e": "AQAB",
		"x5c": ["MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhu/qrZq0fkKBQlq7Dnx6cmoMWumXWHtLTKxuKwPCBr+iZggYhB7L9qs5Ni3bwaQjVx85dh96eYMhGsGC+9TxY07wy4MGRtCaVIHX+vTbokQX+Ufucxdm3yLcXcOdqq/QzcPsmbZvEMt3B4j8NCSqxPn1aSNma97Hqb1tVZGwBIHqQf1H2sgdhlEKpm3l3SszucJpkwG2TO6/qj1JRzrYWWVVZVTMmQsSjNRM7owQfbzVSu5Kzzxkyffq+hDEL5AAKEJr1u4dTjBSB43HfJ3keW44mGTe9eEBFtXrtb3mkFwQ29qCkSJIF563U7AWDTxRoZiEgJyIrt/72hzhGaF1KwIDAQAB"],
		"alg": "RS256",
		"kid": "20161115-00:00:00"
	}, {
		"kty": "RSA",
		"n": "AImEIdkKVhOQrIlsXtL1I4ptNeWIVBbYk10OAZIS3EhJKst4CQcriJwpwgpUX3vT66qLGWn1L84uqM7DuVTBofH2MQKJrFlzd70Hdqz0SJzAHap2LqIzaTcICuuL9f5Hc5BELUIrchbvSW6LrdXQRfCJyvQ58p2s1N69c5tc6bAQZmQ2z5N8kRJ-U_9nKlQflqKvtMCxpZtwiNtojQTJNtqnpoixG0709xsMwmbrAxTU39L-tzWRqmjG3vdcbdJJ4tTTudx0WkzOu_xc3n--UvFU0KtlVx1bQjd7wyZucLMGEjaXuVR_MiEyC0L7Anl4Gtis-qE0oW7A4AUdwTMaqZM=",
		"e": "AQAB",
		"x5c": ["MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiYQh2QpWE5CsiWxe0vUjim015YhUFtiTXQ4BkhLcSEkqy3gJByuInCnCClRfe9PrqosZafUvzi6ozsO5VMGh8fYxAomsWXN3vQd2rPRInMAdqnYuojNpNwgK64v1/kdzkEQtQityFu9Jbout1dBF8InK9DnynazU3r1zm1zpsBBmZDbPk3yREn5T/2cqVB+Woq+0wLGlm3CI22iNBMk22qemiLEbTvT3GwzCZusDFNTf0v63NZGqaMbe91xt0kni1NO53HRaTM67/Fzef75S8VTQq2VXHVtCN3vDJm5wswYSNpe5VH8yITILQvsCeXga2Kz6oTShbsDgBR3BMxqpkwIDAQAB"],
		"alg": "RS256",
		"kid": "20160921-00:00:00"
	}]
}
```

**Comment by jsloyer** [comment]
A little go app that validates it, https://play.golang.org/p/Mjg1zUcxw4

**Comment by shaxbee** [comment]
It seems that your sample uses urlencoding with padding, while go-jose uses
RawURLEncoding. Solution here would be to use URLEncoding instead when
decoding base64url type.

**Comment by jsloyer** [comment]
@shaxbee do we need to change the `n` value encoding or can we tell go-jose to use a different type of encoding to decode it?

**Comment by yun-wang** [comment]
@csstaub @shaxbee Thanks for the quick response. I can confirm changing `RawURLEncoding` to `URLEncoding` fixes the decoding error for me.

**Comment by yun-wang** [comment]
I submitted a PR to just retry with `URLEncoding` when `RawURLEncoding` fails, what do you think?

**Comment by yun-wang** [comment]
PR updated with @shaxbee's review comment.

**Comment by csstaub** [comment]
Strictly speaking, the base64url-encoded data in a JWK should not have padding if I understand the standard correctly. See RFC 7515, Section 2. Do you have the option of fixing the producer that is giving you invalid JWK sets? IMHO the JOSE standards are already wonky enough as it is and we'll be better off in the long run to standardize instead of dealing with corner cases like this in every library.

**Comment by yun-wang** [comment]
@csstaub Yeah, I agree. I'll close the PR, and I'll work with the JWK sets producer to get the encoding corrected.
