### ISSUE TITLE
Link to docs?

### ISSUE THREAD

**Issue by zamicol** [square/go-jose#133]
The link for the docs is a little confusing.  Maybe include a direct link in the main README.md?  

https://godoc.org/gopkg.in/square/go-jose.v2

I usually do a `ctrl+f doc` to find the GoDoc.  That returns two mentions of "The Godoc reference" without a link.

**Comment by csstaub** [comment]
The "godoc | version 1" and "godoc | version 2" badges (both blue) link to the Godoc directly. But yeah, it would be nice to have something searchable. I can add extra links to make it more obvious.
