### ISSUE TITLE
Typed Verification Methods

### ISSUE THREAD

**Issue by ben-turner** [square/go-jose#144]
The `JsonWebSignature.Verify` method currently accepts a `interface{}` as a parameter. This makes it not immediately apparent what types are expected. For example, there doesn't seem to be any indication that `symmetricMac` is created with a byte slice instead of a string unless you read the code. This could be fixed with an update to the docs, however this doesn't fit Go idea of "if it compiles, it will run as expected".

By changing to key-specific methods, this will reduce any confusion. One possible configuration could be:
- `JsonWebSignature.VerifyRSA(*rsa.PublicKey)`
- `JsonWebSignature.VerifyECDSA(*ecdsa.PublicKey)`
- `JsonWebSignature.VerifyMAC([]byte)`
- `JsonWebSignature.VerifyWebKey(*JSONWebKey)`

----

Alternatively, the creation of the `payloadVerifier` could be exposed as a function and then called by the user. Eg:

    verifier, err := jose.NewRSAVerifier(key)
    // handle err
    jws := jose.ParseSigned(input)
    payload, err := jws.Verify(verifier)

This way, everything is strongly typed from beginning to end, but the `Verify` method can accept any type of key as long as it's wrapped in a verifier.

**Comment by csstaub** [comment]
Might make sense as a v3 change. Wdyt @philtay @mbyczkowski @mcpherrinm?

**Comment by philtay** [comment]
+1 for the second idea (exposed payloadVerifier). The first one sounds good in theory, but in practice it would mean to also duplicate `DetachedVerify`, `DetachedVerifyMulti` and `VerifyMulti` for a total of 16 new methods.

**Comment by csstaub** [comment]
Here's a pull request for review:
https://github.com/square/go-jose/pull/248

Wonder if we should make the same change to add `NewRSARecipient`, etc. for encryption. Right now we're doing `Recipient{Key: key}` which also lacks type safety.
