### ISSUE TITLE
Support for EdDSA

### ISSUE THREAD

**Issue by pquerna** [square/go-jose#147]
[RFC 8037](https://tools.ietf.org/html/rfc8037) specifies a `EdDSA` signature type along with `Ed25519` and `Ed448` curves: https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms

**Comment by pquerna** [comment]
Sorry this is a dup of #68 more or less :)

**Comment by csstaub** [comment]
Yes, I would love to support ED25519 and ED448! I think there are already pretty good implementations for those in Go, so we'd just need to hook them up.
