### ISSUE TITLE
[Question] how generate/set the kid of JWT?

### ISSUE THREAD

**Issue by etsangsplk** [square/go-jose#150]
The JWT header kid value can be used as hint to identify on the requried Keys. I have seen others to use finger print, thumb print to set the kid.
But it is not immediately obvious how to do it in go-jose?
Can you add that in example????

**Comment by csstaub** [comment]
What are you trying to do? Are you trying to set a key id in the encrypted or signed message?

**Comment by etsangsplk** [comment]
Signing it.

jose.NewSigner(jose.SigningKey{Algorithm: alg, Key: key}, (&jose.SignerOptions{}).WithHeader("Key", id)WithType("JWT")) ????

**Comment by csstaub** [comment]
The header for the key id is "kid". Setting a header value named "Key" obviously won't work. You should read the RFC explaining what JOSE is and how it works.
