### ISSUE TITLE
V2: go get error when using gopkg.in

### ISSUE THREAD

**Issue by vsivsivsi** [square/go-jose#153]
When I run `go get gopkg.in/square/go-jose.v2`
`$go get gopkg.in/square/go-jose.v2`
 `#gopkg.in/square/go-jose.v2`

`../../../gopkg.in/square/go-jose.v2/encoding.go:150: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/encoding.go:161: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:91: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:97: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:169: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:206: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:211: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:216: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:221: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:226: undefined: base64.RawURLEncoding`
`../../../gopkg.in/square/go-jose.v2/jwe.go:226: too many errors`

**Comment by shaxbee** [comment]
You are probably on ancient golang version base64.RawURLEncoding is
available since 1.5
