### ISSUE TITLE
ECDH-ES should use the apu/apv headers in key derivation if present

### ISSUE THREAD

**Issue by NeilMadden** [square/go-jose#162]
According to https://tools.ietf.org/html/rfc7518#section-4.6.2 the ECDH-ES (and +AnnnKW variants) should use the "apu" and "apv" header parameter values (if present) in the key derivation process. Currently ecKeyGenerator.genKey() passes empty byte slices for both of these parameters, ignoring any apu/apv headers that have been set. This causes an incorrect key to be derived.

NB: it is crypto best practice to include at least a hash of both public keys into the key derivation process to avoid some potential problems that might otherwise occur in certain protocol designs. The only way to accomplish this in JOSE is to set the apu and apv claims to a hash of the public keys so that they will be included.

**Comment by csstaub** [comment]
Looking at the code, `ecDecrypterSigner#decryptKey` takes APU/APV values into account when decrypting a message that uses ECDH-ES. Are you requesting that it be possible to set custom values for APU/APV values during encryption? How have you been trying to set them?

**Comment by csstaub** [comment]
Setting them to a deterministic value (e.g. public key hash) would be pretty easy, but allowing custom header values to be passed through would require a bit more work because it would break the existing interface.
