### ISSUE TITLE
No way to read issuer without verifying a JWT

### ISSUE THREAD

**Issue by mikedanese** [square/go-jose#169]
I would like to read the issuer claim of a JWT before and possibly without verifying the signature of the JWT. For this I need some access to an unverified payload. I understand that the library is designed to disallow access to unverified JWS content, but it prevents some reasonable usecases. Is this not possible with the current API or am I missing something? Is it possible to support this usecase while still minimizing the potential for programmer error/security issues?

**Comment by pquerna** [comment]
FWIW we also have a use case where we need to access the unverified headers.  Adding accessors to `JSONWebSignature` would be minimally helpful;  

We can do this in our own code of course: Hacking together a compact form parser isn't that hard -- just period splitting / base64 decoding, but would prefer to keep things in the jose.v2 types if I could.
