### ISSUE TITLE
It is not possible to implement Signer outside of jose

### ISSUE THREAD

**Issue by petercgrant** [square/go-jose#184]
`jose.Signer` is an interface with `Sign(payload []byte) (*JSONWebSignature, error)`

`JSONWebSignature` is a struct where `payload` is unexported.

**Comment by csstaub** [comment]
That's true, but what's your use case here? Why are you trying to roll your own implementation of the signer logic? If it's just for testing you can return a pre-fabbed JWS, or a dummy/empty JSONWebSignature struct

**Comment by csstaub** [comment]
I don't see why you'd need to implement the entire jose.Signer interface for that, you can delegate the actual signing to a real instance of the jose.Signer interface from the lib with just the right key or you can implement https://github.com/square/go-jose/tree/v2/cryptosigner if you have your keys in an HSM or such.

**Comment by petercgrant** [comment]
cryptosigner is not present in gopkg.in/square/go-jose.v2, which is what github.com/coreos/go-oidc imports. Thank you for your patience. I can take it from here.

**Comment by csstaub** [comment]
Yeah, it's not tagged in a release yet, but it will be in the next release when I tag it. You could pull from master in the meantime to do development on it.

**Comment by petercgrant** [comment]
cryptosigner didn't work for me either because the payload is already hashed before calling the signer. I settled on doing the signing outside of this library. I'm using a KMS that performs RS256 as a service (and not much else), so passing it a hashed payload would double-hash it and give the wrong signature. Thank you for the suggestions.

**Comment by jakecraige** [comment]
Are there plans to support external signing in the future? I've run into this recently and didn't find a way to do this yet
