### ISSUE TITLE
How do I decode a JWE with a secret which is a string

### ISSUE THREAD

**Issue by jakelacey2012** [square/go-jose#187]
I have a silly question which I'm struggling to find the answer at looking at the docs, my question is how do I decode a JWE with a secret which is a string?

**Comment by csstaub** [comment]
I'm sorry, I'm not sure I understand your question. But if you're struggling with the docs to the library I would recommend using something simpler, like `nacl` or `libsodium`. This library isn't really meant as a general-purpose encryption/decryption library, it's more for implementing protocols that are standardized to use JOSE message formats. If you just want to encrypt/decrypt some data other libraries will serve you better.

**Comment by jakelacey2012** [comment]
Thanks for the quick response, I'll have a look at those libraries.

But effectively I'm looking for the equivalent of this https://www.npmjs.com/package/node-webtokens in go `jwt.parse(token).verify(key);`
