### ISSUE TITLE
Go1.11 crypto changes in RSA key generation will break TestVectorsRSA

### ISSUE THREAD

**Issue by cybrcodr** [square/go-jose#189]
The following Go 1.11 CL will break TestVectorsRSA.
https://golang.org/cl/64451 crypto: randomly read an extra byte of randomness in some places

Per CL description ...
"""
Code has ended up depending on things like RSA's key generation being
deterministic given a fixed random Reader. This was never guaranteed and
would prevent us from ever changing anything about it.

This change makes certain calls randomly (based on the internal
fastrand) read an extra byte from the random Reader. This helps to
ensure that code does not depend on internal details.
"""

The test is depending on RSA's key generation being deterministic given a fixed random Reader.  This needs to be fixed for Go1.11.

$ go test  -count=10 gopkg.in/square/go-jose.v2
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
FAIL
FAIL    gopkg.in/square/go-jose.v2      0.355s

$ go test  -count=10 gopkg.in/square/go-jose.v1
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
--- FAIL: TestVectorsRSA (0.00s)
    asymmetric_test.go:98: Output does not match expected value (PKCS1v1.5)
    asymmetric_test.go:104: Encryption failed: unexpected EOF
FAIL
FAIL    gopkg.in/square/go-jose.v1      0.193s

**Comment by mcpherrinm** [comment]
Thanks for filing this ahead of go 1.11 release :)

**Comment by csstaub** [comment]
We can probably just delete that test. It's not that important, other tests cover that functionality more than enough.
