### ISSUE TITLE
Improve JWS key management for verification

### ISSUE THREAD

**Issue by bifurcation** [square/go-jose#2]
The current "supply a key to verify with" model for verification is almost always a bad fit.

If a JWS object contains a "jwk" header, then it already has enough information for a verifier to be able to check the signature.  In this case, it should not be necessary to supply a public key to a verifier constructor.

If a JWS object does not contain a "jwk" header, then the verifier should be identifying the key for verification based on other header fields, e.g., "kid".  In this case, a set of keys with attributes would be an appropriate input to a verifier factory, instead of an individual key.

It might be useful simply to add a Verify() and/or Verify([]KeyType) methods to JwsObject.  For example:
https://github.com/bifurcation/gose/blob/master/jws.go#L211

**Comment by csstaub** [comment]
Hi @bifurcation, I'm working on this (and JWK support) in a separate branch right now: https://github.com/square/go-jose/tree/cs/jwk. Feedback is welcome :).

**Comment by bifurcation** [comment]
Hey @csstaub, thanks for the ping, I'll take a look.  BTW, once you've got JWK and JWS working, if you want to take a stab at integrating it with [boulder](https://github.com/letsencrypt/boulder), that would be awesome.

**Comment by csstaub** [comment]
Merged #20, headers now expose JWK and can be used for verification.
