### ISSUE TITLE
Include precomputed RSA values in JSONWebKey.MarshallJSON

### ISSUE THREAD

**Issue by Everlag** [square/go-jose#202]
Currently, go-jose doesn't copy over the pre-computed values(`dp`, `dq`, `qi`) if they exist on that key.

https://github.com/square/go-jose/blob/v2.1.8/jwk.go#L488

This results in an incompatibility with [node-jose](https://github.com/cisco/node-jose/issues/77). This is a rather difficult to debug issue given the opaque error node-jose generates, `unsupported algorithm`

I'm preparing an associated PR.

**Comment by Everlag** [comment]
Resolved in https://github.com/square/go-jose/pull/203

**Comment by csstaub** [comment]
Released in v2.1.9
