### ISSUE TITLE
Do not set kid header if empty string

### ISSUE THREAD

**Issue by nkristianto** [square/go-jose#211]
i am sign using JWS and found in the header part, "kid" value is always included
is there a way to exclude this header?

**Comment by csstaub** [comment]
Sorry, it's unclear to me what you're talking about. Do you have code to reproduce the issue?

**Comment by bang9211** [comment]
I found the issue.
After I signed and fullseirialize some data, kid header is created in protected header.
if you decode the protected header using base64 “kid”:”” is existed even I didnt make it.
it is caused the part of relation with jwk.

**Comment by csstaub** [comment]
Actually looks like we fixed this in #227
