### ISSUE TITLE
Support JSONWebKeySet in JSONWebEncryption.Decrypt

### ISSUE THREAD

**Issue by shaxbee** [square/go-jose#215]
I plan to implement support for JSONWebKeySet as argument to simplify usage with OpenID provided keysets. Would you be interested in pull request?

**Comment by csstaub** [comment]
Hi @shaxbee, we're always interested in quality pull requests :) I'm not familiar with the particular use-case here, but if you think it's useful it sounds good to me.

**Comment by csstaub** [comment]
Merged in #218
