### ISSUE TITLE
Sign with no Protected header in Flattened JWS JSON Serialization syntax

### ISSUE THREAD

**Issue by jsha** [square/go-jose#22]
By my reading of the code, it looks like the unprotected header field is not supported in [Flattened JWS JSON Serialization](https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#page-22). I'd like to add support: We are using it in https://github.com/letsencrypt/boulder to indicate which key was used to sign a message, and we'd like to port Boulder to use go-jose. Any objections?

Thanks,
Jacob

**Comment by csstaub** [comment]
Hi @jsha, no objections to adding support! Pull requests are definitely welcome :)

**Comment by jsha** [comment]
After further investigation, the problem was not the unprotected header but the lack of any Protected header. Fix in https://github.com/square/go-jose/pull/27.
