### ISSUE TITLE
Support the "b64" header parameter

### ISSUE THREAD

**Issue by philtay** [square/go-jose#225]
https://tools.ietf.org/html/rfc7797#section-3

Currently there is no way to sign the payload *not* encoded in base64. That's a serious limitation when the service you're sending the signatures to requires `b64=false`. If `SignerOptions.ExtraHeaders` has `b64` key with a `false` value then the payload should not be encoded.

**Comment by mbana** [comment]
Hello, I'm also interested in this issue. Is there a workaround that one can use?

**Comment by csstaub** [comment]
This is not supported at present, and I have no plans to implement this. However, pull requests to add support for this are welcome.

**Comment by mbana** [comment]
@csstaub does this look like the right place to add the check https://github.com/square/go-jose/blob/v2/signing.go#L257. Sorry, I am familar with the library as I just started using it today. I will give it a try nevertheless.

**Comment by csstaub** [comment]
That's roughly the right place for signing, but you'd also need to implement it in Verify so message signed with b64=false can be read correctly.

**Comment by philtay** [comment]
@mbana this ugly hack works for signing with `b64=false` (but not for verifying, of course): https://github.com/philtay/go-jose/commit/2f5574262d8d56cff66a1da6a916073856a0b111
I think the `b64` header should be supported by the `SignerOptions` struct.

**Comment by mbana** [comment]
Thanks. Yeh, I figured out how to do it. I'll track to make a pull request when I have time.

**Branch:** https://github.com/banaio/go-jose/tree/v2_support_the_b64_header_parameter_issue_225
**Diff:** https://github.com/square/go-jose/compare/v2...banaio:v2_support_the_b64_header_parameter_issue_225

Use case:

* https://medium.com/syntaxa-tech-blog/open-banking-message-signing-b4ab4f7f92d1
* https://medium.com/syntaxa-tech-blog/more-open-banking-message-signing-fe461f0a627d

**Comment by philtay** [comment]
@mbana if you make the PR today we can work on it together. i have some spare cycles till Monday
