### ISSUE TITLE
Proposal: Use semantic versioning

### ISSUE THREAD

**Issue by mbyczkowski** [square/go-jose#246]
As we're adopting Go modules with the upcoming version 3 of go-jose, it might be a good time to adopt semantic versioning (specifically https://semver.org/spec/v2.0.0.html).

Benefits:
- Semver clearly communicate intent with each release (especially with regards to breaking changes)
- Go modules utilizes semver already ([more here](https://github.com/golang/go/wiki/Modules#semantic-import-versioning)), so this will work well for every Go module user
- Major version change will mean updating import paths (that's how Go modules work); patch and minor version change should be safe from the API compatibility perspective - should be encouraging for users to update their version of go-jose.
- Given the work already started on V3, it should be no work to adopt semver (see [releasing Go modules with V2 or higher](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher))

If we decide to adopt it, (I think) this practically means that:
- We'll have to be more strict about making our releases (i.e. making sure we adhere to the semver spec)
- We'll state expectations with regard version support and deprecations. I think going forward we should support latest major release version + 1.

Bonus, if we can provide a note on migration from V1 and V2 to V3.

Thoughts @csstaub?

**Comment by philtay** [comment]
> Major version change will mean updating import paths (that's how Go modules work)

AFAIK using Go modules + semver means to never have to change import paths again. The version is specified in the `go.mod` file and it's independent from the path.

**Comment by csstaub** [comment]
I agree with the proposal @mbyczkowski.

@philtay: I think Mat B. is right here, if I understand https://github.com/golang/go/wiki/Modules#semantic-import-versioning correctly the version will need to be part of the import path like `import "github.com/square/go-jose/v3"`. So if we'd want to bump to v4, it would change to `import "github.com/square/go-jose/v4"`. Right?

**Comment by mbyczkowski** [comment]
Correct, the wiki page says:
> If the module is version v2 or higher, the major version of the module _must_ be included as a `/vN` at the end of the module paths used in go.mod files (e.g., `module github.com/my/mod/v2`, `require github.com/my/mod/v2 v2.0.0`) and in the package import path (e.g., `import "github.com/my/mod/v2/mypkg"`).

> If the module is version v0 or v1, do _not_ include the major version in either the module path or the import path.

So if a library is unversioned, unstable or on 1.x release, the import path would not include the major version. V2 and higher means manually updating import paths.

The reasoning for this behavior is that, IIRC, given a breaking change in a library, 2 versions of the same dependency can be imported in the module, while the migration takes place (not to mention that updating dependency should be as safe as possible - bumps to minor versions should theoretically not break apps).

**Comment by philtay** [comment]
Uhm, IMO it's a bit ugly but it seems "the standard". The `module` directive of `go.mod` should be `github.com/square/go-jose/v3` instead of `github.com/square/go-jose`. All import statements should be updated as well. Ref.: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by mbyczkowski** [comment]
You're correct @philtay. I just realized this also means all relative paths in go-jose have to use `github.com/square/go-jose/v3` as import paths.
