### ISSUE TITLE
Consider adding PKCS11 support

### ISSUE THREAD

**Issue by csstaub** [square/go-jose#25]
As a possible enhancement, it would be nice to have support for doing decryption/signing on HSMs via PKCS11. Possibly with some sort of wrapper around https://github.com/miekg/pkcs11.

**Comment by jsha** [comment]
Note: If you want to wrap PKCS11 for signing, you may find this higher-level package (which wraps miekg/pkcs11) easier to use: https://github.com/letsencrypt/pkcs11key.

**Comment by csstaub** [comment]
That looks super useful. Thanks @jsha!

**Comment by csstaub** [comment]
Should be possible to do this now via the opaque signer interface
