### ISSUE TITLE
'EdDSA' alg header field inconsistent with jwt/ruby-jwt

### ISSUE THREAD

**Issue by zblach** [square/go-jose#260]
Constructing a JWT with an ed25519 key constructs a header where `alg` has a value of 'EdDSA'. 

This is incompatible with JWTs generated by https://github.com/jwt/ruby-jwt, which use 'ED25519' as an 'alg' type.

**Comment by csstaub** [comment]
That looks like a bug in ruby-jwt. 

Per RFC 8037 it should be EdDSA:
https://tools.ietf.org/html/rfc8037
