### ISSUE TITLE
Unsecured (plain) JWT

### ISSUE THREAD

**Issue by kdimak** [square/go-jose#264]
There are `signed` and `encrypted` JWT builders to build JWS and JWE correspondingly, as well as combined `nested` builder. 
Please add support for an unsecured (plain) JWT builder.

**Comment by csstaub** [comment]
Sorry, but I'll have to exercise my executive veto on this one. I think insecure JWTs are a mis-feature of the standard and I don't think we should ever support them. If your data is not signed or encrypted it has no business being in a JWT.

**Comment by kdimak** [comment]
Got it! Thank you for the reply.
