### ISSUE TITLE
Release new minor version

### ISSUE THREAD

**Issue by maraino** [square/go-jose#266]
### Description
The [commit](https://github.com/square/go-jose/commit/467354d5a5957a305c7c9fae4c71259c81bcc1af) that fixes the salt length in the PS256, PS384, and PS512 signatures is not included in the last release, please, release a new version with that fix.

**Comment by cgarvis** [comment]
Any way you could include https://github.com/square/go-jose/pull/245 in your minor version release?

**Comment by cgarvis** [comment]
thank you @csstaub and @maraino

**Comment by csstaub** [comment]
Tagged and released: https://github.com/square/go-jose/releases/tag/v2.4.0

**Comment by maraino** [comment]
Thanks.
