### ISSUE TITLE
JSONWebEncryption.ParseEncrypted: error in cryptographic primitive

### ISSUE THREAD

**Issue by erdarun** [square/go-jose#276]
Steps to reproduce

> object, err = ParseEncrypted(jwe_token)
> if err != nil {
>     panic(err)
> }

JWE Header

> {"kid":"0c6e8cac-d231-4157-838c-f0e3421a36cb","enc":"A256GCM","alg":"dir"}

Entire JWE
> eyJraWQiOiIwYzZlOGNhYy1kMjMxLTQxNTctODM4Yy1mMGUzNDIxYTM2Y2IiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..vztrHSZ3PFoolcHs.Fw7PoQROLRFanPrs1RCdZ7csZzC5vIjoTT_j0BTnbLa9kFP4T4WSkl4UmxNHO3WXN4mH19bQ9IQfDwPM2DFK2rwBAeSulZL8OXBmU4vm0XZ5iIOF6qpVu2US4R_F42OuVYKk-uWYEHi1yor99P08b2WH5u2sxsvs4Fjo12qR-x3l7eu02wk6Cp83Urv0nHC6vis9B9OHHTCV0lsR8RTmHSDgvVPXh9zBWPAAtvjr9M0LRMeuh2NyqQI7jkmI5TjLJOE2iSD2n6zWCPIN1WH3N0Ty4r9KYH09HytqhFCOpR-dtmYDbv76fy7ZZ9VfJCaZk8GHUPdwiIq6xMOz3lWoB2v4Ek1WtX-d3W9qsau8xKXeGGmEFcjFXrHifkjcmE7Y_RFfCDym9iYv-ahwO3HK8Np_FFRKpTs4vsrBxgHmyoHw7vvgmMpax6HzehTximAVkaL9eRTUoVTfErBibAwsK9O3aBHMZLuznNy5Pg-o-P1N34UAEEat6hZOHQq6o4xdtt86G328zQzoaWOgXraioLT4tUiqQkJOJ1ksKJYMwl27oyUtyEfV9DgBISY1cI3efY57UqHgrkdZJj0hqb4hdK9SQuvljChZIwHjps95cbDNg4isd3HaEi9ANZOHtepx5Mm4-Mz4aF3rpfpgH48wKHeyj6_89VxrshdaJ5upZyiyo5FaeKSzAXJwARWcb9OeV1RlKh6apOstZnv0JGhk4mxNyNQmz09w9qaSIatlnkpUcnXrPdHNgTVkw8bJtkApCU3UmZWQDKuVYff6qRiieffnmVOmMP2LyJzMSUWkfVMCTfVDFKgTEMW8TVirRL1elA-y7xqR-bvI14tUtntEIGLlXZbmgZq4BM233YmNLUlJudD2F0tHHyORXxgEButiNYd8fjrgovzucPQxZH5HajsSx_ib6LhB6VcmYGkfiXM26GU-UeFDSw1CPlGt9jo1SeJrJgHZPxua8euY3DfqVxEa5ctdcl5cyHWKDCqFMXkJQJ6HZEVry7PdzoUbO93V8LwpAtilkJXoG3to0HwHHF-vs1nJNGIycHKDKWW6WUW9UiwiQHcxjKvk3G6t3R-NOzLqHZ6UO2vqgA_pqfjwlH9nAfQYValqhXUA1j5Unn9DtysSFzzDn4d9Jarkv3iyfrCv49XUi2t6WuKB9tLUrkHNEGWvv5V8t2k7tfX0VfbatqXAR0a0JVai0AZ5eGO-afIewu18ik3zBfQGuccD1i7JoN45jzyqIFAp8_-0HQZVAq1zDnwfBXpK0jNENnySBVBgYCMpz3sZCoRA74AX9J63iP6hOr8c49tOQZrRM-6BIuHrYT-dEr_j-Lb7tjTKu8PtRje51F3_9on-QgVsIUqb9sGiieyOSn_KMYQd35g_JynjOZBFeiwbyRCqNFx-VqnKrtG3PWvODxzvPXE1Ezhdgnu7M3lj2ZBCix90jJ5vOtae8cgmm3HUlLhxNkIotFAxJED8eKw9R3eyLXuCmlH9PvrhNkmJA5Fo8TqeUVVDVJ_BdbZVTPD2TsySysbwzyHF9yGFg8IkdlHnHLADW4dETcEW3RfKVviSdCNF_YnyMSjaIj5rcn7cjEr55hFgYKD_gs-VqKp7qF-yJG1h3l70vW2w6N2ERkXUbkqS_V4vHr_IoK58WYOOzm8BHft935hN3uzMzyQ3UvPdC3Kbr2de3XXmo63zJDN9nZRLaCqklyH0QGG_KKFurhZ7tuMgIRWpQKYjJpsJSDs.t3_e0WQ8VUYIyeZkM2hlpA

**Comment by therealsphinx** [comment]
What is the impact here?

**Comment by therealsphinx** [comment]
@erdarun What is the impact here?
