### ISSUE TITLE
Changes are not consistently applied to v2 and v3

### ISSUE THREAD

**Issue by mbyczkowski** [square/go-jose#290]
I have found a few cases were we have not been applying changes to either v2 or master branch (current v3 development). To make things clearer, I propose we only create PRs targeting master and then cherry-pick to v2 (when applicable):
- If PR for v3 also makes sense for v2 (say a bug-fix or a backward-compatible feature), let's label the PR `V2-Cherry-Pick` (or something similar), so we know a cherry-pick should be made onto v2 (and a person merging should create a separate commit with cherry pick).
- If PR is only to fix v2, then PR should be labeled accordingly, e.g. `V2-Only`.

Here's the list of (potential) discrepancies I have found to date:

**master-only PRs:**
- #242
- #250
- #269
- #274
- #280
- #289

**v2-only PRs:**
- #261 (but #257 is opened and awaiting some more involved refactoring)
- #279 
- #282

**Comment by csstaub** [comment]
I like this @mbyczkowski, let it be so.

**Comment by mbyczkowski** [comment]
Cool, I have created the labels and opened #291 and #292 to back-port and port-forward the missing changes. The remaining PR (#261) is being tracked already in #257.
