### ISSUE TITLE
How to use ED25519 ?

### ISSUE THREAD

**Issue by fungiboletus** [square/go-jose#297]
Hi,

I'm trying to test go-jose with ED25519 (or EdDSA) but I'm doing it wrong. I mostly get errors such as `unsupported key type/format`. Do you have any example about how to use it ? From reading the code and the tests, it looks like it cannot be used like ECDH_ES.

**Comment by mbyczkowski** [comment]
I wonder if you're seeing issues related to #253

**Comment by advanderveer** [comment]
For me it was because i was using the std lib ed25519. If you are using v2 of go-jose you have to make sure to use golang.org/x/crypto/ed25519 instead.

**Comment by fungiboletus** [comment]
I'm just loading the public key from a PEM file. It's time is indeed ed25519 from golang.org/x/crypto/ed25519. However I don't know how to provide it to `jose.NewEncrypter`. It always return `unsupported key type/format`.

**Comment by fungiboletus** [comment]
Okay my bad, it looks like ED25519 is for signing, no encryption.
