### ISSUE TITLE
Valid method on JSONWebKey always returns false for symmetric key JWKs

### ISSUE THREAD

**Issue by tdyas** [square/go-jose#314]
There is no switch case for symmetric key JWKs in the `Valid` method on `JSONWebKey`. Thus, the default case returns `false` even for an ostensibly valid JWK, while, if there were no default case at all, the final statement would have returned `true`.

What is the intended behavior in this case? I can submit a PR for that behavior.

https://github.com/square/go-jose/blob/8ccb8a19e8094e234b5387186ac16f08f160c505/jwk.go#L457-L460

**Comment by soumasandesu** [comment]
The switch block is a section of short-circuits which filter out those keys which is not within standard. It's correct to `return true` if none of inverse assertions are matched.

As a symmetric key of JWTKey`.Key` is a raw type (i.e. `[]byte` or `[]uint8`), the `switch $type {}` should make `case byte` return true explicitly to make the whole validation valid. (?🤔)

**Comment by csstaub** [comment]
Yeah this is reasonable to add for validation, it should check for []byte and also make sure the length of the byte array is a valid key size (e.g. 16, 24, 32, etc bytes)
