### ISSUE TITLE
TestOpaqueKeyRoundtripJWE is very slow, times out on slow platforms

### ISSUE THREAD

**Issue by mwhudson** [square/go-jose#326]
Hi,

We're seeing persistent timeouts testing new versions of this package on armhf in Ubuntu:

https://autopkgtest.ubuntu.com/packages/g/golang-gopkg-square-go-jose.v2/groovy/armhf

There are a few slow tests but TestOpaqueKeyRoundtripJWE appears to be the slowest. Does it make sense to skip this test when -short is passed or something?

Cheers,
mwh

**Comment by csstaub** [comment]
Yeah, you can skip those if they're too slow for your platform. You can also increase the timeout.
