### ISSUE TITLE
CertificateThumbprintSHA1 undefined

### ISSUE THREAD

**Issue by gnurik** [square/go-jose#339]
Trying to access property `CertificateThumbprintSHA1` doesn't compile, but I can't figure out why and I see that it was introduced in 2.5.0 (https://github.com/square/go-jose/compare/v2.4.1...v2.5.0#diff-adb413cfea72e48e90449f9604b1472d63b22160f9c1230bb22517ece6a0fa89R86). Property `Certificates` seems fine but it was there prior to 2.5.0 so is this some weird release/gopkg.in issue?

```
import (
	jose "gopkg.in/square/go-jose.v2"
)

func getKey(key *jose.JSONWebKey) string {
	return key.KeyID + string(key.CertificateThumbprintSHA1)
}
```

Compiler gives this error:
```
key.CertificateThumbprintSHA1 undefined (type *"gopkg.in/square/go-jose.v2".JSONWebKey has no field or method CertificateThumbprintSHA1
```

**Comment by pippo** [comment]
Hi @gnurik. I'm not able to reproduce the issue with v2.5.0.
Could you, please, make sure you've got version `v2.5.0` or above in your `$GOPATH`?

**Comment by gnurik** [comment]
realized that the latest import I should be using is actually `gopkg.in/go-jose/go-jose.v2` instead of `gopkg.in/square/go-jose.v2`, seems ok now.

**Comment by gnurik** [comment]
had an old version referenced in go.mod also, 🤦
