### ISSUE TITLE
Can we manually validate token using CA certificate Public key?

### ISSUE THREAD

**Issue by smartaquarius10** [square/go-jose#350]
Team,

I have a use case of open id connect. In this we are not receiving public key in any header like x5c, x5u or x5t.

Is it possible to manually verify jwt using CA public key. If yes, could any one please share a block of code.

Thank you

**Comment by csstaub** [comment]
There's examples in the Go API documentation for how to verify a signature or token given a public key.

**Comment by smartaquarius10** [comment]
@csstaub , if possible, could you please share the link. Tried searching on google but no luck.

**Comment by csstaub** [comment]
The API docs are linked in the readme: https://github.com/square/go-jose
