### ISSUE TITLE
Consider adding "use" key for JWKs

### ISSUE THREAD

**Issue by lestrrat** [square/go-jose#54]
I have seen that for some of the JWK-related libraries out there the "use" key in the JWK is required to find the correct key to use for sign verification and what not.

For example, JWK like:

```
{ keys: [ { "kty": "RSA", ... other elements } ] }
```

Fail, but this works

```
{ keys: [ { "use": "sig", "kty": "RSA", ... other elements } ] }
```

Now, for the stuff I'm doing, I want to generate the JWK file from the RSA private key on the fly. So I do something like the following:

```
type MyJWK struct {
   *jose.JsonWebKey
   Use string
}

json.Marshal(MyJWK{ Use: "sig", JsonWebKey: &jose.JsonWebKey{...} })
```

and for serialization/deserialization, I'm jumping through hoops, which is doable, but it sure would be nice if `jose.JsonWebKey` just did it for me. Thoughts?

**Comment by csstaub** [comment]
We can definitely add a `Use` field to the `jose.JsonWebKey` struct, should be pretty simple. Feel free to open a pull request to add it to the struct.
