### ISSUE TITLE
Ideas for version 2

### ISSUE THREAD

**Issue by csstaub** [square/go-jose#64]
Would love to clean up the interface for a go-jose.v2 release. Ideas welcome!

**Comment by csstaub** [comment]
So far, what I would like to change:
* make signers/encrypters/etc immutable (options can only bet set when creating a new object)
* allow setting options through an options struct so we can add more things over time
* allow per-message headers to be set? e.g. add "SignWithHeaders(..., headers)"

**Comment by csstaub** [comment]
Working on v2 branch: https://github.com/square/go-jose/tree/v2, comments welcome.

**Comment by shaxbee** [comment]
Planned improvements for claims setting in jwt.Builder.

Separate Claims method into PublicClaims(cl Claims) and PrivateClaims(cl interface{}).
Those two methods would merge claims with existing ones also preventing private claims from overriding public ones. 

For private claims map[string]interface{} would be used as a storage in builder and reflect would be used to extract fields following encoding/json conventions.
If value passed to PrivateClaims call implements json.Marshaler the encoder will first marshal message into byte slice and then unmarshal it into aforementioned map.

Comments / thoughts?

**Comment by shaxbee** [comment]
Or to keep it simple we can make PrivateClaims(cl map[string]interface{}) the only way to set claims.

**Comment by ericchiang** [comment]
@shaxbee I'm a little confused by the motivation behind the public and private claim logic. Isn't the main distinction about naming? Why are these things that need to be expose to the end user?

Also we've personally had issues with map[string]interface{}[0], and now favor using explicit structs instead. No preference, but just a word of warning.

[0] https://github.com/coreos/dex/issues/418

**Comment by shaxbee** [comment]
@ericchiang This stems from conversation around #82, where @csstaub mentioned that it would be preferable to have typesafe methods instead, I don't have strong opinion on that thought. 

As for using map[string]interface{} as claims storage in builder it is necessary to support merging when Claims are called multiple times. I wrote utility to marshal structs into map, honouring json tags. The date storage is not an issue as jwt package cames with its own NumericDate type.

Regards,
Zibi

**Comment by ericchiang** [comment]
Okay, thanks for the explanation :)
