### ISSUE TITLE
Registered claims

### ISSUE THREAD

**Issue by yawn** [square/go-jose#67]
Are you interested in supporting [registered claims](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1) in this project? Or should I create a separate repository implementing (at least a subset of those) on top of `go-jose`?

I'd like to support (at least) `exp` and `nbf`.

**Comment by csstaub** [comment]
Yeah, I think this could make a good addition for go-jose.v2, if you're interested in contributing it.

**Comment by yawn** [comment]
No chance to get in into the current version? I'd build it as an independent package.

**Comment by csstaub** [comment]
Sure, we can merge it in anytime. I was just mentioning v2 because I'm planning to break the interface for that anyway, so if you feel interface-breaking change would be needed it could go in there.

**Comment by csstaub** [comment]
See `jwt` sub-package in the v2 branch for a dev version.
