### ISSUE TITLE
CFRG ECDH and signatures in JOSE 

### ISSUE THREAD

**Issue by csstaub** [square/go-jose#68]
Support for: https://datatracker.ietf.org/doc/draft-ietf-jose-cfrg-curves/

**Comment by darkk** [comment]
As far as I see, support added in #154 is a bit incomplete, `IsPublic()` and `IsValid()` always return `false`.

**Comment by csstaub** [comment]
Sounds like a bug. @darkk could you open a new issue with some steps to reproduce?

**Comment by darkk** [comment]
Heh, seems, I was late. I see that it's already fixed. Thanks, @csstaub! :-)

**Comment by csstaub** [comment]
Yes, this should work now (for ed25519). It's still fairly new, let us know if you run into issues with it.
