### ISSUE TITLE
Go's JSON parser is case-insensitive

### ISSUE THREAD

**Issue by jsha** [square/go-jose#73]
As pointed out at https://www.ietf.org/mail-archive/web/json/current/msg03763.html, Go's JSON parser is case-insensitive, which can lead to differences in interpretation between go-jose and libraries in other languages.

One possible workaround, mentioned in that thread, is to parse into a `map[string]string`, where the key names will be based on exact match.

**Comment by csstaub** [comment]
Parsing as a `map[string]string` would work, but it's super annoying to parse messages that way. Maybe we could just fork `encoding/json` and make a case-insensitive version? That way we could also make changes to reject JSON blobs with duplicate keys.

**Comment by rolandshoemaker** [comment]
:+1: for forking `encoding/json`, none of these bugs (or... idk, quirks?) will be fixed during the go1 lifetime to retain backwards compatibility.
