### ISSUE TITLE
how to verify with jwk

### ISSUE THREAD

**Issue by kmulvey** [square/go-jose#77]
If I use signer.Sign() which by default includes the public key in the jwk header how can I use this to verify? Verify() expects a key, but I want to use the key thats already in the token.

**Comment by csstaub** [comment]
You can parse the message and then extract the key from the signature header if you must. But beware that you need to make sure the key is trusted (such as by verifying the thumbprint). In general, it is preferable to always know which key you expect a message to be signed with ahead of time.
