### ISSUE TITLE
gopkg imports github.com repo 

### ISSUE THREAD

**Issue by ericchiang** [square/go-jose#78]
Importing this package from the gopkg import requires downloading the github repo as well. Not a bug, but it seems odd to having the versioned import path downloading the latest from github for the sub repos.

```
$ go get -v gopkg.in/square/go-jose.v1
Fetching https://gopkg.in/square/go-jose.v1?go-get=1
Parsing meta tags from https://gopkg.in/square/go-jose.v1?go-get=1 (status code 200)
get "gopkg.in/square/go-jose.v1": found meta tag main.metaImport{Prefix:"gopkg.in/square/go-jose.v1", VCS:"git", RepoRoot:"https://gopkg.in/square/go-jose.v1"} at https://gopkg.in/square/go-jose.v1?go-get=1
gopkg.in/square/go-jose.v1 (download)
github.com/square/go-jose (download)
github.com/square/go-jose/json
gopkg.in/square/go-jose.v1
```

**Comment by csstaub** [comment]
Yeah, I haven't set up versioning for the `cipher` and `json` subpackages. I should probably do that just for the sake of consistency, though I don't really intend to change anything in there.
