### ISSUE TITLE
please tag formal releases

### ISSUE THREAD

**Issue by onlyjob** [square/go-jose#83]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by csstaub** [comment]
What's your use-case here? Since Go doesn't really support dynamic linking, packaging `square/go-jose` by itself doesn't really make sense. If you maintain a Go project that depends on us, please use vendoring to pin to a specific version. You can use the `v1` branch via `gopkg.in/square/go-jose.v1`, for which we guarantee backwards-compatibility (the `v2` branch is still in development).

**Comment by onlyjob** [comment]
Packaging. In Debian instead of vendoring (which IMHO should be condemned as it throws away 20+ years of best practice in software engineering) we have to reuse standalone packages. Packaging makes a lot of sense because it reduces duplication and allows to run tests properly on build -- a something often neglected for vendored libraries. On this instance _square/go-jose_ is going to be introduced as (build) dependency.
I suppose we could use mock-up date-based versions if you believe that there API breakage is unlikely. However even in this case versioning can provide additional benefits to encourage vendoring of a particular (e.g. latest _stable_) release contrary to random unreleased snapshots.
I hope that makes sense. :)

**Comment by csstaub** [comment]
Ah, I see. That is entirely reasonable. I've pushed tag `v1.0` to repo (it matches the current head of the `v1` branch). I don't plan to make any interface-breaking changes to the `v1` branch in the future (the point of having a branch is to keep it stable), though I suppose I may bump the tag if anything new is added. If you want to verify the GPG signature, my public key can be found on my website at [css.bio](https://css.bio).

**Comment by onlyjob** [comment]
Awesome! Thank you very much. :)
