### ISSUE TITLE
x5c / x5t parameters

### ISSUE THREAD

**Issue by arekkas** [square/go-jose#95]
Is it possible to use [x5c](https://tools.ietf.org/html/rfc7517#section-4.7) parameters with go-jose? I want to marshall a RSA private key along a x509 certificate (for HTTP over TLS).

Example: https://tools.ietf.org/html/rfc7517#appendix-B

**Comment by csstaub** [comment]
There's not field for it in the struct right now, but it should be fairly simple to add. I can take a look at adding this next week maybe. Or if you want to take a shot at it, [pull requests are welcome](https://github.com/square/go-jose/blob/master/CONTRIBUTING.md)!

**Comment by arekkas** [comment]
Hey I would be glad if you could take a look because I have a lot of work right now. If you don't find the time I will look at this in the next weeks / month

**Comment by arekkas** [comment]
I took a quick look but I'm not really sure where to begin. I guess we need to add a type assertion for `tls.Certificate` in `MarshalJSON`. Then, marshal the private key using `fromEcPrivateKey` or respectively `fromRsaPrivateKey`. My question is how to encode `tls.Certificate.Certificate` in DER encoding - or is the byte slice already in DER encoding?

I guess it would look something like (pseudo):
```go
raw, err = fromEcPrivateKey(cert.PrivateKey)
raw.X5c = base64(DER(cert.Certificate))
```

Am I on the right path here? Additionally, how to tests? :D

**Comment by csstaub** [comment]
You want `x509.Certificate`, not `tls.Certificate`. The only changes that would be required are the logic for marshalling/unmarshalling the list of `[]*x509.Certificate` a caller puts into the `X5c` field of a `jose.JsonWebKey` struct. But while we're at it, should probably also add support for `X5t` and such.

**Comment by arekkas** [comment]
Would `base64(x509.Certificate.Raw)` be enough for x5c? And `base64(sha1(x509.Certificate.Raw))` for x5t?

**Comment by csstaub** [comment]
Yes -- also `base64(sha256(certificate.Raw))` for `x5t#S256`.

**Comment by csstaub** [comment]
Although now that I think about it, setting `x5t` and `x5t#S256` should actually be up to the caller.

**Comment by arekkas** [comment]
Ok so only x5c for now?

**Comment by csstaub** [comment]
No I think the fields should be added to the struct, just serialize them directly.

**Comment by arekkas** [comment]
I am confused. Do you mean that the developer using go-jose is responsible for x5t? I think I will stick to x5c for now - I'm not confident with the according RFCs and such.

**Comment by arekkas** [comment]
Let's continue this in #96

**Comment by arekkas** [comment]
resolved by https://github.com/square/go-jose/pull/97
