### ISSUE TITLE
jwt: expose key headers

### ISSUE THREAD

**Issue by ericchiang** [square/go-jose#98]
Currently the "jwt" package does not expose the jose.Header fields of the JSONWebToken. This means you can't match on keyIDs to determine which key pair signed the token (and verify appropriately).

I propose adding a "Signatures" field to the JSONWebToken to mirror the JSONWebSignature.

**Comment by csstaub** [comment]
Sounds good to me. Note that `v2` is still unstable and the interface can change (the [releases tab](https://github.com/square/go-jose/releases) shows what's tagged as stable).

**Comment by ericchiang** [comment]
Yep. Understand that this may change :)

**Comment by shaxbee** [comment]
I can take care of this.

**Comment by csstaub** [comment]
Just merged #99, closing this. Please ping/re-open if something is missing.
